language: node_js
node_js: node
addons:
  chrome: stable

jobs:
  include:
  - stage: make-goldens
    script: npm run test:diff:golden && npm run test:diff:golden:commit

deploy:
  provider: releases
  api_key: "$GITHUB_RELEASE_TOKEN"
  on:
    tags: true
env:
  global:
  - SAUCE_USERNAME: Desire2Learn
  - OWNER_NAME: Brightspacehypermediacomponents
  - REPO_NAME: consistent-evaluation
  - DEFAULT_INCREMENT: patch
  # GITHUB_RELEASE_TOKEN
  - secure: KcSP70Xdy8yk0EWKIZTzlZW+XMgl+FagGis0f2Hba4/0n1reQqV75GoWmmRhDixRIeL60lz+da03mYXGD1HsMFLp4hM/V4Fjzf7VSGHQI/yor0/EJGc/SBnno8mXaBR8kSGO3ZCBcRlxcILBLaBs7oWPJT9d8hJYpNLKL2FQpAQhwoJTL02SYODusZmkw2vpr7KM8I5MiPX7rRB5YhxzbRWEgV91T9CRaKGFztD5dFjRoIQmaU/HTB6RYU+yuSn7BhlqaHz1q/yJt4IpYIdVnnc9QY390mrfWvxjOsieeXLXhl8tk3bImY0RM3h/S7Nj26c5S18VBgSOGn76jw2zxlC11Xx3FQ7moDs0dwQg6F74hYw9v6kKbiNnQQ0zskSz+D3oLyf3QlOQx809aeN6PxtnT6n9cDs195B8nC+xTyQHnq0RTNS6fPrMVkEms3VbRzYuobqcwhLcmnQEznJVEPYCjK9OZp8j76ZFdRWvJXJDsCi/jonS32eACxqquUlZW/CJA/rKehLbx8ifMgrjBLzONuumG/MAliqo9CuJtkV783/Sm/56UXUFXRgGZ4r9EaiVYKnQANx6W5wXzcWaPsJBaiT9QNlHExwfvvMGUdNsiVkRo9+kDydEGyf8fDKTSXBbbguopAtmwUpQf16Hyp8nUkRDvATLILATfc8Pwe0=
  # VISUAL_DIFF_S3_ID
  - secure: iq8Ufr+nvW/t01wSbpxlxZRmok79j9rR7YW/00yhFQd9UP76bdvd0yCrOOgN8+jNkEBkwo5fPnEnhtDH8GQDM4Tu89LGE5E6MfpoUhwuZOdDB5ZsT55IssilRh9x/pXanL190xEBHI7AeYEob3vG1KTLW57uk9cWRc791P0LKV7+vPHUiGUTwJnphzw48yNyT5s5pqUlOpJYHFN7c8UlRY/xUkvFZohbahM09lt7tVaa2K1S/OmWjCpbSKJBdgtu/1F6YWrpXO7I/CLYtdF8us3HkAZQPwDyHpxaqrOnshfITuZ2NFThCT4UFAfQHsaCzgm+PDPUsMB2z5pROm+tqCiJQ6K5zJsWAtHhRSu8PnLH94TDbo7zISAzOyHQKXixiTnHrmf3UtB3Qb2o4e+w7xBqH24eMiuevz3Q6M8lT9SR2kJ1D6HfVTe2rtYte5U9cJC0YCmnr23yWmr+wDNL3+rjYMhgqZ49t5qydnv3fiDnVu3pr4PKMZ7AVUhLJBT33Gn0DTdkh8cOt5cQX4CMFlFzjz5JSSPEipnmTajZ+2KEy1m1AQmqAeBagmY9dBylr6LMRY5jyAhRfekMllcPJfOGbF1u58R5Mi/FeamimCDUrHCoLy2uUjfXtynIk7HuhAJ762aNfqrB7Yy5qMd6iDWX+/7NxZeolqJ+RadpsU8=
  # VISUAL_DIFF_S3_SECRET
  - secure: XE1yIXDgu2Wrp17Azx3ZY4DcH6Bo3lZh/eMTLHoHS4UhrJf2AwO8dNavWcvD04hJaloQWs4WlizgnKsJJPvmVoM19ffnb+JEcvGtLwam9hgPTzw0dU1StOtFrUy1ZJS+0f4F8uLZXjcxWuTAjVxlzxHPM0HO+ClMznnXkB2crlflxW2hMaCLpvNzG2mVkmb07i/wjM0g5XGJo6RdKauCRYTf/hyzXqaDBGR555VazZOWx8tx22TOFtAAs0cLjXFpSe93/uN+GEqShGkuM1ZYsa/+NVlBzH0kqUovvod4ThckaNcE9RaWWKpxIMzHgglqUCm8B8FMqQ+/t6DhX9kwsX49aDUhARh/lsWB7ht4axDvS7wHIOrdsZE88D2zlX0kGt+M2936gwgw5SkkKH/xHQakcOSSPXoRL9pRia8JOUTE7MMmgrpFNaiExval/pdknEpFGWBHMBgZwImLtOUfSdJ5WbnE35coWuW0o4eLTdKQwF4dkn/4zJhDZIJCFXx/8GlhDOvsWzKvSMXZsnVwegKHHTvGouMBcHZiV/z/IKHiF6KY6H9yt+5dUxbA7D4XnNixPoNYNLsoiJpGYxWkZ6vfstqV6OjSnbpwuOMPYhqZ+1SP87s608NWehQV0WFhNK6jQOXdUdb3fHuXZ7+RYK1LqKQWWATGHIPJlTlzNgs=
  # SAUCE_ACCESS_KEY
  - secure: qCi9PBCl0eZ6s0lWOhIaQRoGhRMaPDXq9ALegxP8xVp4N33FZTqfy94dMKqcucLMcVDoPDvBQetFJbSWhPY66kKqEcNthXosNRwMGA314CJMXEFSFwP2kB13VxHuiVnxU3uLsM4BLXPIdwYVzOL8ArCb5MUM9x+wTALwwJ+/wxHE66aS1odMTX8V9zfcA75xp//Ame6imQ3WB+3UxivbKyyUa9RCTXJZyc+uzdy3TdD/Cm6m10Gj1GeZxgS27aPU+POkTvlom20LawB9TpjoeZqLlPfWB4+LJECWPDFO9wTUMlaXsmrXQ3DonpWymc4oxOn0hePrIT5bGN1880Th33E2xco9lGWM/rtKb1X8j/cAINcx+/5EtBYzQKQtIjeplN3TFMnJ4J2x7lQN0InOrhf0CWRncym3M9EfedNv/7+dJ+nB72PnCMMEKGl49IoYAuqSte52Jq8IA+wUy39HSSqeK1ysIo2ufNI/+agXEIgSp+2NnpN2knV28eah2MttbbR6rTbEQGrBb9WRm0O5M1hEebdCVQILdmVDY8nZkGXXEYHIUH7pzs02tRlbPFKhyKrXNPpm5QJ84ohOlDDioy4l/jrxPJJQTjmJrLrrdSr2CJjXK/KZCaeKJEhSWdvzH9xCDn6VrmECoyh3SzHYaNGyoJ2vIaCqcGQ+B+vXYJg=
